title: Create VCN
description: VCN Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"

#####################################

# Variable Groupings

#####################################

groupings:

  - title: "Select Compartment"
    variables:
      - ${compartment_ocid}
      - ${tenancy_ocid}
      - ${region}
    
  - title: "VCN Configuration"
    variables:
      - ${Hub_vcn_cidr_block}
      - ${Hub_vcn_display_name}
      - ${Hub_vcn_dns_label}
      - ${NLB_subnet_cidr_block}
      - ${NLB_subnet_display_name}
      - ${NLB_subnet_dns_label}
      - ${NLB_subnet_prohibit_public_ip_on_vnic}
      - ${Untrust_subnet_cidr_block}
      - ${Untrust_subnet_display_name}
      - ${Untrust_subnet_dns_label}
      - ${Untrust_subnet_prohibit_public_ip_on_vnic}
      - ${Management_subnet_cidr_block}
      - ${Management_subnet_display_name}
      - ${Management_subnet_dns_label}
      - ${Management_subnet_prohibit_public_ip_on_vnic}
      - ${Trust_subnet_cidr_block}
      - ${Trust_subnet_display_name}
      - ${Trust_subnet_dns_label}
      - ${Trust_subnet_prohibit_public_ip_on_vnic}
      - ${Non_Prod_vcn_cidr_block}
      - ${Non_Prod_vcn_display_name}
      - ${Non_Prod_vcn_dns_label}
      - ${Dev_subnet_cidr_block}
      - ${Dev_subnet_display_name}
      - ${Dev_subnet_dns_label}
      - ${Dev_subnet_prohibit_public_ip_on_vnic}
      - ${Test_subnet_cidr_block}
      - ${Test_subnet_display_name}
      - ${Test_subnet_dns_label}
      - ${Test_subnet_prohibit_public_ip_on_vnic}
      - ${Prod_vcn_cidr_block}
      - ${Prod_vcn_display_name}
      - ${Prod_vcn_dns_label}
      - ${Prod_subnet_cidr_block}
      - ${Prod_subnet_display_name}
      - ${Prod_subnet_dns_label}
      - ${Prod_subnet_prohibit_public_ip_on_vnic}
      - ${project_tag}
  

variables:

#####################################

# Common Compartment

#####################################
  compartment_ocid:
    type: oci:identity:compartment:id
    visible: true
    title: Select the Compartment to deploy resources
    description: Choose the Compartment where to deploy the resources

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: false
    title: Region
    description: Region
 

#####################################

  # Hub VCN Configuration

#####################################

  Hub_vcn_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.0.0/16"
    title: Hub VCN CIDR
    description: Choose a CIDR for Hub VCN
   
  Hub_vcn_display_name:
    type: string
    required: false
    visible: true
    default: "Hub vcn"
    title: VCN name
    description: Choose a VCN name

  Hub_vcn_dns_label:
    type: string
    required: false
    visible: true
    default: Hub vcn
    title: Hub vcn dns label

  NLB_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.1.0/24"
    title: NLB subnet CIDR
    description: Choose a CIDR for NLB subnet

  NLB_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "NLB subnet"
    title: NLB subnet display name

  NLB_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "NLB subnet"
    title: NLB subnet dns label
    description: Choose NLB subnet dns label
   
  NLB_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: NLB subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses 

  Untrust_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.2.0/24"
    title: Untrust subnet CIDR
    description: Choose a CIDR for Untrust subnet

  Untrust_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Untrust subnet"
    title: Untrust subnet display name

  Untrust_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Untrust subnet"
    title: Untrust subnet dns label
    description: Choose Untrust subnet dns label
   
  Untrust_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Untrust subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses

  Management_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.3.0/24"
    title: Management subnet CIDR
    description: Choose a CIDR for Management subnet

  Management_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Management subnet"
    title: Management subnet display name

  Management_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Management subnet"
    title: Management subnet dns label
    description: Choose Management subnet dns label
   
  Management_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Management subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses 
 
  Trust_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.4.0/24"
    title: Trust subnet CIDR
    description: Choose a CIDR for Trust subnet

  Trust_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Trust subnet"
    title: Trust subnet display name

  Trust_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Trust subnet"
    title: Trust subnet dns label
    description: Choose Trust subnet dns label
   
  Trust_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Trust subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses 
 
#####################################

  # Non_Prod VCN Configuration

#####################################

  Non_Prod_vcn_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.1.0.0/16"
    title: Non_Prod VCN CIDR
    description: Choose a CIDR for Non_Prod VCN
   
  Non_Prod_vcn_display_name:
    type: string
    required: false
    visible: true
    default: "Non_Prod vcn"
    title: NonProd name
    description: Choose a Non_Prod VCN name

  Non_Prod_vcn_dns_label:
    type: string
    required: false
    visible: true
    default: NonProd vcn
    title: Non_Prod vcn dns label

  Dev_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.1.1.0/24"
    title: Dev subnet CIDR
    description: Choose a CIDR for Dev subnet

  Dev_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Dev subnet"
    title: Dev subnet display name

  Dev_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Dev subnet"
    title: Dev subnet dns label
    description: Choose Dev subnet dns label
   
  Dev_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Dev subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses
 
  Test_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.1.2.0/24"
    title: Test subnet CIDR
    description: Choose a CIDR for Test subnet

  Test_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Test subnet"
    title: Test subnet display name

  Test_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Test subnet"
    title: Test subnet dns label
    description: Choose Test subnet dns label
   
  Test_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Test subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses 
 
#####################################

  # Prod VCN Configuration

#####################################

  Prod_vcn_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.2.0.0/16"
    title: Prod VCN CIDR
    description: Choose a CIDR for Prod VCN
   
  Prod_vcn_display_name:
    type: string
    required: false
    visible: true
    default: "Prod vcn"
    title: Prod VCN name
    description: Choose a Prod name

  Prod_vcn_dns_label:
    type: string
    required: false
    visible: true
    default: Prod vcn
    title: Prod vcn dns label

  Prod_subnet_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.2.1.0/24"
    title: Prod subnet CIDR
    description: Choose a CIDR for Prod subnet

  Prod_subnet_display_name:
    type: string
    required: false
    visible: true
    default: "Prod subnet"
    title: Prod subnet display name

  Prod_subnet_dns_label:
    type: string
    required: true
    visible: true
    default: "Prod subnet"
    title: Prod subnet dns label
    description: Choose Prod subnet dns label
   
  Prod_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    required: false
    visible: true
    default: false
    title: Prod subnet prohibit public ip on vnic 
    description: Check the box if the VNICs created in this subnet have private IP addresses 



