title:  Terraform Input Variables
description:  Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"

#####################################

# Variable Groupings

#####################################

groupings:



  - title: "Select the Target Tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}

  - title: "Creat dd-monitoring compartment"
    variables:
      - ${dd_monitoring_compartment_name}
      - ${dd_monitoring_compartment_description}
      - ${dd_monitoring_enable_delete}

  - title: "Creat dd-hub compartment"
    variables:
      - ${dd_hub_compartment_name}
      - ${dd_hub_compartment_description}
      - ${dd_hub_enable_delete}

  - title: "Creat dd-network compartment"
    variables:
      - ${dd_network_compartment_name}
      - ${dd_network_compartment_description}
      - ${dd_network_enable_delete}

  - title: "Creat dd-security compartment"
    variables:
      - ${dd_security_compartment_name}
      - ${dd_security_compartment_description}
      - ${dd_security_enable_delete}

  - title: "Creat dd-nonprod compartment"
    variables:
      - ${dd_nonprod_compartment_name}
      - ${dd_nonprod_compartment_description}
      - ${dd_nonprod_enable_delete}    

  - title: "Creat sub-compartments dd-nonprod-dev and dd-nonprod-tst under dd-nonprod compartment"
    variables:
      - ${dd_nonprod_dev_compartment_name}
      - ${dd_nonprod_dev_compartment_description}
      - ${dd_nonprod_dev_enable_delete}
      - ${dd_nonprod_tst_compartment_name}
      - ${dd_nonprod_tst_compartment_description}
      - ${dd_nonprod_tst_enable_delete}

  - title: "Creat sub-compartments dd-appdev and dd-dbdev under dd-nonprod-dev compartment"
    variables:
      - ${dd_appdev_compartment_name}
      - ${dd_appdev_compartment_description}
      - ${dd_appdev_enable_delete}
      - ${dd_dbdev_compartment_name}
      - ${dd_dbdev_compartment_description} 
      - ${dd_dbdev_enable_delete}

  - title: "Creat sub-compartments dd-apptst and dd-dbtst under dd-nonprod-tst compartment"
    variables:
      - ${dd_apptst_compartment_name}
      - ${dd_apptst_compartment_description}
      - ${dd_apptst_enable_delete}
      - ${dd_dbtst_compartment_name}
      - ${dd_dbtst_compartment_description}   
      - ${dd_dbtst_enable_delete}       

  - title: "Creat dd-prod compartment"
    variables:
      - ${dd_prod_compartment_name}
      - ${dd_prod_compartment_description}    
      - ${dd_prod_enable_delete}

  - title: "Creat sub-compartments dd-appprod and dd-dbprod under dd-prod compartment"
    variables:
      - ${dd_appprod_compartment_name}
      - ${dd_appprod_compartment_description}
      - ${dd_appprod_enable_delete}
      - ${dd_dbprod_compartment_name}
      - ${dd_dbprod_compartment_description}    
      - ${dd_dbprod_enable_delete} 

#####################################

# Common Compartment

#####################################
variables:

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    title: Region
    description: Region

  compartment_ocid:
    visible: true
    title: compartment ocid
    description: compartment ocid

#####################################

  # Creat dd-hub compartment

#####################################

  dd_hub_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-hub"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_hub_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-hub"
    title: "compartment description"
    description: "Provide compartment description."

 
    
#####################################

  # Creat dd-network compartment

#####################################

  dd_network_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-network"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_network_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd_network"
    title: "compartment description"
    description: "Provide compartment description."

  
#####################################

  # Creat dd-monitoring compartment

#####################################

  dd_monitoring_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-monitoring"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_monitoring_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-monitoring"
    title: "compartment description"
    description: "Provide compartment description."

  

#####################################

  # Creat dd-security compartment

#####################################

  dd_security_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-security"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_security_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-security"
    title: "compartment description"
    description: "Provide compartment description."

  
#####################################

  # Creat dd-nonprod compartment

#####################################

  dd_nonprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-nonprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_nonprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-nonprod"
    title: "compartment description"
    description: "Provide compartment description."


  #### compartment dd-nonprod-dev###  

  dd_nonprod_dev_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-nonprod-dev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_nonprod_dev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-nonprod-dev"
    title: "compartment description"
    description: "Provide compartment description."

  
#### compartment dd-nonprod-tst ####

  dd_nonprod_tst_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-nonprod-tst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_nonprod_tst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-nonprod-tst"
    title: "compartment description"
    description: "Provide compartment description."

 
 #### dd-appdev #####

  dd_appdev_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-appdev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_appdev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-appdev"
    title: "compartment description"
    description: "Provide compartment description."
  
 
#### compartment dd-dbdev ######

  dd_dbdev_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-dbdev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_dbdev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-dbdev"
    title: "compartment description"
    description: "Provide compartment description."


 
 #### dd-apptst #####

  dd_apptst_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-apptst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_apptst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-apptst"
    title: "compartment description"
    description: "Provide compartment description."

 
 #### dd-dbtst ######

  dd_dbtst_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-dbtst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_dbtst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-dbtst"
    title: "compartment description"
    description: "Provide compartment description."

  
 
##### compartment dd-prod #####

  dd_prod_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-prod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_prod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-prod"
    title: "compartment description"
    description: "Provide compartment description."



#### compartment dd-appprod ####

  dd_appprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-appprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_appprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-appprod"
    title: "compartment description"
    description: "Provide compartment description."


#### compartment dd-dbprod #####

  dd_dbprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "dd-dbprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dd_dbprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dd-dbprod"
    title: "compartment description"
    description: "Provide compartment description."
  
 