name: ci

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      
      - name: 'Write Config & Key Files'
        run: |
         mkdir ~/.oci
         echo "[DEFAULT]" >> ~/.oci/config
         echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
         echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
         echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
         echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
         echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
         echo "key_file=~/.oci/key.pem" >> ~/.oci/config
         echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
      - name: 'Install OCI CLI'
        run: |
         curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
         chmod +x install.sh
         ./install.sh --accept-all-defaults
 
