name: ci

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      
      - name: Install oci-cli
        uses: bytesbay/oci-cli-action@v1.0.2
        with:
          user: "${{ secrets.OCI_USER }}"
          fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
          tenancy: "${{ secrets.OCI_TENANCY }}"
          region: "${{ secrets.OCI_REGION }}"
          api_key: |
            ${{ secrets.OCI_KEY_FILE }}
          verbose: true

      - run: cat ~/.oci/config

      - run: oci -v
      - run: |
         mkdir -p ~/.oci
         echo [DEFAULT] >> ~/.oci/config
         echo user="${{ secrets.OCI_USER }}" >> ~/.oci/config
         echo fingerprint="${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
         echo key_file=~/.oci/oci_api_key.pem >> ~/.oci/config
         echo tenancy="${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
         echo region="${{ secrets.OCI_REGION }}" >> ~/.oci/config
         echo "${{ secrets.OCI_KEY_FILE }}" >> ~/.oci/oci_api_key.pem
         oci setup repair-file-permissions --file ~/.oci/config
         oci setup repair-file-permissions --file ~/.oci/oci_api_key.pem
