name: Test the run-oci-cli-command action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-running-instances:
    runs-on: ubuntu-latest
    name: Use the run-oci-cli-command to retrieve a list of running instances
    env:
      OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
      OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
      OCI_REGION: ${{ secrets.OCI_REGION }}
      OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
      OCI_COMPARTMENT_NAME: ${{ secrets.OCI_COMPARTMENT_NAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve the OCID of a named compartment in tenancy
        uses: ./
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='${{ secrets.OCI_COMPARTMENT_NAME }}'].id"

      - name: Find instances in the named compartment
        uses: ./
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'

      - name: List the found instances
        run: echo ${{ steps.find-instances.outputs.output }} | jq .
