# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for the Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.

name: 'Deploy Infra stacks in OCI'

on: 
 push:
    branches:
         - "main"
env:
  REGION: "us-ashburn-1"
  BRANCH_NAME: "develop"
  STACK_NAME_COMPARTMENTS: "Deploy VCN"
  WORKING_DIRECTORY_COMPARTMENTS: "VCN"

  REPO_URL: "https://github.com/Karthiga1700/DD-repo.git"
  TF_VERSION: "1.0.x"

permissions:
  contents: read

jobs:

  Deploy-VCN:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Writing config files'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.FINGERPRINT}}" >> ~/.oci/config
          echo "compartment_ocid=${{secrets.COMPARTMENT_OCID}}" >> ~/.oci/config
          echo "region=${{secrets.REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=${{secrets.key.pem}}" >> ~/.oci/config
          echo "${{secrets.PRIVATE_KEY_FILE}}" >> ~/.oci/key.pem
       
      - name: 'Install OCI CLI'
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          #exec -l $SHELL
          echo " Fixing file permissions and testing oci"
          /home/runner/bin/oci setup repair-file-permissions --file ~/.oci/config
          /home/runner/bin/oci setup repair-file-permissions --file ~/.oci/key.pem
          echo " oci os ns get"
          /home/runner/bin/oci os ns get
         
